name: 🙋Question
description: Ask questions about the project
title: "[Question]: "
labels: ["Question"]
body:
  - type: markdown
    attributes:
      value: |
        Please enter the topic of your question above. Example [Question]: Image copyright issue
  
  - type: input
    id: minecraft-version
    attributes:
      label: Enter the Minecraft version
      placeholder: e.g., 1.20.1, 1.19.4, etc.
    validations:
      required: true
  
  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed description (Drag support images here)
      description: Please provide a detailed description of your question. You can drag and drop images directly into this text area.
      placeholder: Describe your question in detail...
    validations:
      required: true
